export const CHANGE_NAME_VALUE = 'CHANGE_NAME_VALUE';

export const CHANGE_EMAIL_VALUE = 'CHANGE_EMAIL_VALUE';

export const CHANGE_PASSWORD_VALUE = 'CHANGE_PASSWORD_VALUE';

export const CHANGE_CONFIRM_PASSWORD_VALUE = 'CHANGE_CONFIRM_PASSWORD_VALUE';